services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    environment:
      MYSQL_DATABASE: 'ibsys-retail-manager'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: .
    ports:
      - "8080:8080"
    container_name: api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/ibsys-retail-manager
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: development
    depends_on:
      - db
volumes:
  db_data:
