name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  JAVA_VERSION: 17
  MYSQL_DATABASE: ibsys-retail-manager
  MYSQL_ROOT_PASSWORD: root

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      db:
        image: mysql:5.7
        environment:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - '3306:3306'
        expose:
          - '3306'
        volumes:
          - db_data:/var/lib/mysql
    volumes:
      db_data:
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: maven
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
